sudo: false
language: ruby
dist: trusty
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: 'xvfb-run -a bundle exec rake'
rvm:
  - 2.2.5
before_install:
  - gem install bundler -v 1.12.5
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
