sudo: false
language: ruby
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: 'xvfb-run -a bundle exec rake'
rvm:
  - 2.2.5
before_install:
  - gem install bundler -v 1.12.5
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
